### ISSUE TITLE
luid-daterange - use moments locale to define what is the first day of the week

### ISSUE THREAD

**Issue by lucienbertin** [LuccaSA/lucca-ui#118]
i just checked and for angular-i18n, a french week starts on sunday

https://cdnjs.cloudflare.com/ajax/libs/angular-i18n/1.4.8/angular-locale_fr-fr.js

```json
    "FIRSTDAYOFWEEK": 0, // sunday
```

and that not really the case so you cant use this for the starting-day in the datepickers in the `luid-daterange`

instead use the [moment locale](http://momentjs.com/docs/#/i18n/) which is betterer

we're already supes dupes dependent on moment for a lot of other things so let's continue the trend

**Comment by lucienbertin** [comment]
fixed in next release - [2.0.7](https://github.com/LuccaSA/lucca-ui/releases/tag/2.0.6)

**Comment by Poltuu** [comment]
maybe you should start an issue on angular
