### ISSUE TITLE
Add radio support for the element `.lui.input` 

### ISSUE THREAD

**Issue by vergerf** [LuccaSA/lucca-ui#169]
New input type radio style (like checkbox's one)
Florian

**Comment by lucienbertin** [comment]
for the checkbox we have this

```html
<div class="lui checkbox">
	<input type="checkbox" id="yesno" checked />
	<label for="yesno">yes or no?</label>
</div>
```

so the target synthax is this

```html
<div class="lui radio">
	<input type="radio" id="yesno" checked />
	<label for="yesno">some label</label>
</div>
```

**Comment by lucienbertin** [comment]
@Clotilde you might need to add icons to the lucca-icons font for that

**Comment by lucienbertin** [comment]
@Clotilde I created the branch [radio.input](https://github.com/LuccaSA/lucca-ui/tree/radio.input) for you

to make it work checkout the branch, then do these command lines

```
npm install
bower install
tsd install
grunt debug
```

you can then access your local [demo page](http://localhost:9001/demo/#/sass#lui-input) where i added a section _Fancy radio_

I also created a scss file and all the stuff that comes with it, it is the file `scss\core\elements\_input.radio.scss` and it is a copy paste of the `_.input.checkbox.scss` file with every `checkbox` changed into `radio`. if you uncomment all it looks alright minus the missing icons

i'm available if you need help

**Comment by lucienbertin** [comment]
in `_input.radio.scss` line 29 and 35, if you use an existing icon it works

```scss
@include lui_make_icon("jumping cc");
```

**Comment by lucienbertin** [comment]
added in release [2.0.15](https://github.com/LuccaSA/lucca-ui/releases/tag/2.0.15)
