### ISSUE TITLE
Lucca ui Select dropdown isn't correctly placed

### ISSUE THREAD

**Issue by vergerf** [LuccaSA/lucca-ui#190]
Hi,
The dropdown doesn't display correctly on lucca-ui select:
![capturefiggo](https://cloud.githubusercontent.com/assets/5548413/13992467/83766934-f11c-11e5-853d-135b29f5a858.PNG)

I can fix this by adding a top: Xpx, But I think it isn't the best way to fix it.

I think this was supposed to be corrected on #149

**Comment by vergerf** [comment]
#https://github.com/LuccaSA/lucca-ui/issues/149

**Comment by bpaugam** [comment]
Is this issue still relevant ? Should it be closed ?

**Comment by bpaugam** [comment]
Chances are, it will be fixed in 3.0
