### ISSUE TITLE
It would be nice if luid-user-picker gets the coloration of invalid when it's ng-invalid

### ISSUE THREAD

**Issue by vergerf** [LuccaSA/lucca-ui#191]
if I put the attribute required on luid-user-picker and no user is specified, border aren't colored in red (like the invalid class).

**Comment by pjerem** [comment]
Hello,
Pourquoi cette issue a t'elle été fermée ? Y a t'il eu un correctif @sanlucca ?

**Comment by sanlucca** [comment]
La PR #334 devrait avoir fixer ça oui

**Comment by pjerem** [comment]
Super ! cc @vergerf :)
