### ISSUE TITLE
.progress-bar is not behind a .lui and is "polluting"

### ISSUE THREAD

**Issue by GMouron** [LuccaSA/lucca-ui#292]
When upgrading my version of lucca-ui from 2.0.x to 2.3.0 on a page where I had a "homemade" `.progress-bar`, this one got funked by the lucca-ui styles.

**Comment by lucienbertin** [comment]
will be fixed for the [release 2.3.1](https://github.com/LuccaSA/lucca-ui/releases/tag/2.3.0)

is it urgent ? cuz @bpaugam is on holiday and should be proof reading (even though its a fairly minor fix)

**Comment by GMouron** [comment]
No, I got around it, it can wait
