### ISSUE TITLE
[The grid] hide columns

### ISSUE THREAD

**Issue by Clotilde** [LuccaSA/lucca-ui#297]
We should support _0_ when the width of columns is defined, to hide a column in some devices.

For example, if a thin column with no important content is displayed on large devices, it can be useful to hide it on smaller ones, like this : 
`<div class='lui column mobile-0 tablet-3 desktop-2 large-1'>`

**Comment by bpaugam** [comment]
The "{device}-hide" classes should do the trick.

In your example, "mobile -hide" hides the column on mobile-sized displays.
