### ISSUE TITLE
[The grid] Same height columns

### ISSUE THREAD

**Issue by Clotilde** [LuccaSA/lucca-ui#298]
Add a parameter that force columns of **a same row*** to have the same height.

— *  same row ≠ same parent

**Comment by bpaugam** [comment]
That would be fairly easy to achieve through flexbox model, but it's IE10 at best.

**Comment by Clotilde** [comment]
Any chance we should achieve that with a little bit of javascript? 

(I can wait for an answer until tomorrow, enjoy your day off 😜  )

**Comment by bpaugam** [comment]
JS for presentation purposes = evil !

I'm sure @lucienbertin would agree :p

**Comment by lucienbertin** [comment]
agreed

**Comment by bpaugam** [comment]
Fixed in release 3.0
