### ISSUE TITLE
[.lui.button.flat] No color on :hover

### ISSUE THREAD

**Issue by Clotilde** [LuccaSA/lucca-ui#299]
Hovered _flat buttons_ should not have colored background.
We should only change the text hue instead (darken).

**Comment by bpaugam** [comment]
Should it support colorscheme ?

ie a 'primary flat button' should be light yellow by default, and a darker color on hover ? Or should it only be colored on hover ?

**Comment by Clotilde** [comment]
No. Flat buttons are just links with the same padding/margin/borders than colored buttons, so that they can be perfectly aligned with colored buttons when they're side by side. Let's keep it grey (but not ugly and sad!)
