### ISSUE TITLE
lucca-layout improvments

### ISSUE THREAD

**Issue by lucienbertin** [LuccaSA/lucca-ui#301]
- make that the `main-header` support the class `lui top stuck` without stepping over the `main-navigation`
 - be sure that the `main-nav` works without `app-logo`

**Comment by bpaugam** [comment]
Fixed in release 3.0

**Comment by thomasjoet** [comment]
étant donné qu'en version mobile le banner n'affiche pas le titre "annuaire", on peut garder le nom de l'application en haut du menu en version mobile
![image](https://cloud.githubusercontent.com/assets/10392236/18506903/5c403224-7a6e-11e6-96cb-01f28fade9de.png)

**Comment by lucienbertin** [comment]
@thomasjoet english plz
