### ISSUE TITLE
nguibs-popover support property `popover-title`

### ISSUE THREAD

**Issue by lucienbertin** [LuccaSA/lucca-ui#31]
in the [ui-bs popover example](https://angular-ui.github.io/bootstrap/#/popover) there is a property `popover-title` that is not currently supported
```html
<div class="lui button" popover="some text" popover-title="title" popover-class="lui nguibs-popover">
  click me
</div>
```

**Comment by bpaugam** [comment]
Fixed in the soon-to-be-merged `eradicating.bootstrap` branch.
