### ISSUE TITLE
textarea - support for multiple rows

### ISSUE THREAD

**Issue by lucienbertin** [LuccaSA/lucca-ui#317]
my html is thusly, see the [textarea formly template](https://github.com/LuccaSA/lucca-ui/blob/3.0-dist/ts/formly/fields/textarea.html)

```html
<div class="lui field">
	<div class="lui input">
		<textarea ng-model="stuff" rows="4"></textarea>
		<label for="{{::id}}">{{ options.templateOptions.label }}</label>
	</div>
</div>
```

but the height is set by the css so the `rows` attribute is ignored

**Comment by bpaugam** [comment]
Fixed
