### ISSUE TITLE
luifNumber - default input to zero when undefined

### ISSUE THREAD

**Issue by earrouvi** [LuccaSA/lucca-ui#35]
Trying to format an undefined value with luifNumber returns ",undefined" instead of "0".

Possible fix in filter:
```
if (_input === undefined) {
    _input = 0;
}
```

**Comment by lucienbertin** [comment]
almost ready, some problem with `NaN` that slipped through the cracks.

**Comment by lucienbertin** [comment]
fixed and updated [demo page](http://luccasa.github.io/lucca-ui/filters.html/#luifNumber), enjoy :)
