### ISSUE TITLE
Group icon replaced by cross icon

### ISSUE THREAD

**Issue by MaximeBonobots** [LuccaSA/lucca-ui#351]
Not sure what is the real issue, but here is a description:

In Cleemy we load lucca-ui 3.0.4 and banner.css including lucca-icons.

In banner.css, "group" icon is defined [like this](https://github.com/LuccaSA/ilucca/blob/rc/static/lucca/banner/banner.css#L1120) (which leads to a correct "group" icon).

But lucca-ui is overridding it with:
```sh
.lui.icon.group[class*=group]:before {
    content: "\e05d";
}
```
which is a *cross* icon

Any idea ?

**Comment by MaximeBonobots** [comment]
Due to conflicting versions of lucca-icons loaded in the same page, fixed with encapsulation of the versions with css selector.

```
“It works on my machine” always holds true for Chuck Norris.
```

**Comment by bpaugam** [comment]
Because the banner is doing it wrong. It should depend on lucca-icons but instead chose to copy-paste the definitions. Thus, the banner gets screwed every time there is a breaking change in the lucca-icons release cycle.

**Comment by MaximeBonobots** [comment]
Yes, discussed with @Poltuu, closing this issue
