### ISSUE TITLE
[forms] add compact style

### ISSUE THREAD

**Issue by Clotilde** [LuccaSA/lucca-ui#356]
For large forms (ie directory > user files), we need to _rollback_ to old fields : labels are outside the field itself, next to them, fields have borders, label and field are displayed side by side.

This will allow the user to : 
- have a clear idea of which fields need to be filled
- see more than half a dozen fields without scrolling

**Comment by Clotilde** [comment]
This doesn't mean we have to kill the _material design like_ forms, but we should offer a _compact mode_ for specific admin views.

**Comment by lucienbertin** [comment]
pr #376
