### ISSUE TITLE
IE9 spinner fallback path breaks webpack bundle

### ISSUE THREAD

**Issue by MaximeBonobots** [LuccaSA/lucca-ui#362]
This code in _loader.scss:
```sh
       $lui_ie_fallback_loader: "../../../dist/ie_fallback_spinner.gif";
	// IE9 support
	@include lui_target_IE9 {
		&:before { border: none; }
		&:after { border: none; margin: 0; background: transparent url("#{$lui_ie_fallback_loader}") no-repeat center center; background-size: contain; }
	}
```
causes 'Cannot find module "../../../dist/ie_fallback_spinner.gif"' when bundled with ng cli. It works fine with "./ie_fallback_spinner.gif".

- Is this fallback used ?
- If it is, can we add a relative partial path parameter ?

**Comment by GuillaumeNury** [comment]
Même problème ! J'ai copié le fichier où il fallait en attendant...
