### ISSUE TITLE
[buttons] allow keyboard use

### ISSUE THREAD

**Issue by Clotilde** [LuccaSA/lucca-ui#384]
Lucca-ui buttons should be handled with keyboard : 

- **tab** key should set the focus on the next button
- **alt** + **tab** keys should set the focus on the previous button
- **enter** key sould trigger the action of the focused button

**Comment by lucienbertin** [comment]
@bpaugam there is no style for `:focus` in _button.scss

@Clotilde the keyboard support is automatic if you use the right tag

```html
<button class="lui button">will work</button>
<div class="lui button">won't work</button>
```

**Comment by PaulAndreLOUIS** [comment]
I think real problem here is @Clotilde wants a button to be focused when opening a luisNotify

**Comment by lucienbertin** [comment]
@jeremie-lucca there is no style for `:focus` in _button.scss
