### ISSUE TITLE
`a.wired.button` now displays link color

### ISSUE THREAD

**Issue by bpaugam** [LuccaSA/lucca-ui#413]
![image](https://cloud.githubusercontent.com/assets/10196812/24648835/417a5054-1925-11e7-834e-e23dec5348e5.png)

**Comment by jeremie-lucca** [comment]
It looks ok for me in the reporting tab.
Does it appear on a specific page / browser / ... ?

![image](https://cloud.githubusercontent.com/assets/25581936/24699562/b4a1c218-19f4-11e7-98a2-9d2f7f9e4351.png)
