### ISSUE TITLE
nguibs-modal in a namespaced distrib

### ISSUE THREAD

**Issue by lucienbertin** [LuccaSA/lucca-ui#46]
nguibs modal is appended to the body and as such is outside the namespaced part of the html, so the style is not applied.

find a way to inject nguibs style to the modal even if people are namespacing the distrib of lucca-ui

**Comment by bpaugam** [comment]
Additional prefix can be specified in theme overrides for modal - cf https://github.com/LuccaSA/lucca-ui/commit/fb473bce20cc92c6eab603b203e7887b2488a5ae

**Comment by bpaugam** [comment]
Actually, it did not work, After much research and a ticket at the sass project repo, I came up with a solution (code ain't pretty, but the use is much simpler).

The only thing you need to do is to add your '#namespace' selector as a class to the angular ui bootstrap modal and backdrop (with the hash remove), like so:

```scss
#myAwesomeApp{ @import "bower_components/lucca-ui/scss/lucca-ui.namespace"; }
```

```javascript
    var modalInstance = $uibModal.open({
      templateUrl: 'myModalContent.html',
      controller: 'ModalInstanceCtrl',
      windowClass: "myAwesomeApp {optional_nguibs_prefixed_class}",
      backdropClass: "myAwesomeApp {optional_nguibs_prefixed_class}"
      }
```
