### ISSUE TITLE
have colors 'error', 'success' and 'warning'

### ISSUE THREAD

**Issue by lucienbertin** [LuccaSA/lucca-ui#5]
i liked that in the previous version you had colors for error, success and warning. in this version you just have primary, secondary and yellow, red, green, orange. no blue btw. the colors you chose seems kinda arbitrary

i know there is some kind of way to override the color module to add the colors i want when i import lucca-ui but you didn't properly document it yet so....

**Comment by lucienbertin** [comment]
added with commit [f627882bbc0c45f53bae8351f6fd8584bfa824c9](https://github.com/LuccaSA/lucca-ui/commit/f627882bbc0c45f53bae8351f6fd8584bfa824c9)

**Comment by lucienbertin** [comment]
might have to be reverted because it conflicts with `icon success` so 
`lui button icon success` (a button neutral with the icon success) is not the same thing as `lui success button icon check` (a button success with the check icon)

**Comment by bpaugam** [comment]
Color handling changed radically, and these extra `success`, `warning` and `error` color definitions were removed (partly due to naming conflicts with icons).

If you want to support such color definitions, just add a `definitions/colors.overrides.less` file in your theme directory, and define your color scheme as such:

``` less
@lui_colors:
    // colorName color textOverColor isLightTextOverDarkBackground
    grey #666 #fff true,
    light #ccc #666 false,
    primary #FFC900 #666 false,
    secondary #f60 #fff true,
    red #f60 #fff true,
    orange #f90 #fff true,
    green #5cb85c #fff true,
    yellow #FFC900 #666 false;
```
