### ISSUE TITLE
user-picker - display me first

### ISSUE THREAD

**Issue by lucienbertin** [LuccaSA/lucca-ui#50]
Would it be possible to always have the choice "me" as first choice in the dropdown, whatever search text is entered

for example in timmi/validation, i am looking at the hoursheets awaiting vergnory's approval and i want to go back to the one awaiting my approval. as of today i must type `luc` to have my name available in the list of choices and select it.

would it be better if the choice `Me` was always available as first choice in something like this

| ro *(that's the search input)* | 
------
| me |
| **ro**main vergnory |
| anne **Ro**umanov |

@bpaugam what do you think ?

**Comment by bpaugam** [comment]
We did this for timmi indeed. My initial idea was to use the native ui-select grouping, but I guess this project is already way past all this?

**Comment by pierop** [comment]
PR #80 - merged
