### ISSUE TITLE
user-picker - display a number next to each result 

### ISSUE THREAD

**Issue by lucienbertin** [LuccaSA/lucca-ui#51]
in the same way we handle customFilter, add the possibility to call a function with this signature
```
var customCnt = function(user) { return int; }
```
and display the returned int next to the names of the available choices like that

| ro *(that's the search box)* |
| ---------- |
| **Ro**main Vergnory `5` |
| Anne **Ro**umanov `2` |

it would be useful to display information contextual to the page, for example the number of expense claim awaiting approbation for each available choice

**Important:** call this function only once you have decided on the 5- displayed choices, not when you still have N users

@bpaugam what do you think

**Comment by bpaugam** [comment]
Yes, yes and yes! I can already see a hell of a ton of use cases.
