### ISSUE TITLE
Add selectedUser in First Position in choices dropdown

### ISSUE THREAD

**Issue by bpaugam** [LuccaSA/lucca-ui#73]
The selected user ain't appearing in the choices !

**Comment by lucienbertin** [comment]
when the current selected user is in the list of choices, before you handle the pagination, you display him as first result with a custom class like `selected` or `active`

**Comment by lucienbertin** [comment]
non options, set it as the standard comportment

**Comment by lucienbertin** [comment]
PR #77 - merged
