### ISSUE TITLE
directive luid-localized-input

### ISSUE THREAD

**Issue by lucienbertin** [LuccaSA/lucca-ui#86]
add a directive allowing to edit/display a variable containing several variables

something like that

```
<luid-localized-input ng-model="myMultiLocalString" ng-changed=""></luid-localized-input>
```
when myMultiLocalString looks something like `en:she loves you yeah! yeah! yeah!|fr:melodie d'amour chante le coeur d'emmanuelle|de:neune und neunzich luftballons`

**Comment by lucienbertin** [comment]
```
<div class="lui fitting input with addon">
	<input type="text" ng-model="internal.fr" ng-change="chnaged()">
	<div class="lui right addon button">FR</div>
</div>
```
clicking on the addon display a dropdown with the supported languages

**Comment by lucienbertin** [comment]
@stubbst, @Clotilde, @bpaugam 

i did [this plunkr](http://plnkr.co/edit/5w46OmJlhoQ3uwutgEaU?p=preview) super fast to give you an idea of what it's gonna look like.

i'm gonna update it slightly to add the dropdown on the  `+` button but not much more

**Comment by bpaugam** [comment]
I thought about it and I think it would be better to show all supported local inputs when clickin on the dropdown button,

**Comment by lucienbertin** [comment]
added in release [2.0.4](https://github.com/LuccaSA/lucca-ui/releases/tag/2.0.4)
